# Generated by Django 6.0.5 on 2026-05-26 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRANSACTION_CREATED', 'Transaction Created'), ('FUNDS_DEPOSITED', 'Funds Deposited'), ('DELIVERY_CONFIRMED', 'Delivery Confirmed'), ('DISPUTE_RAISED', 'Dispute Raised'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('FUNDS_RELEASED', 'Funds Released'), ('REFUND_ISSUED', 'Refund Issued')], max_length=30, unique=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
