# Generated by Django 6.0.5 on 2026-05-26 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=15)),
                ('resolution', models.CharField(blank=True, choices=[('RELEASE', 'Release to Seller'), ('REFUND', 'Refund to Buyer'), ('PARTIAL', 'Partial Release')], max_length=10)),
                ('resolution_notes', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
    ]
